// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Community.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Community.core.Models.Courses", b =>
                {
                    b.Property<int>("coursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("coursId"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("coursId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Community.core.Models.Teacher", b =>
                {
                    b.Property<int>("teacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("teacherId"));

                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.Property<string>("coursName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.HasKey("teacherId");

                    b.HasIndex("CoursesId")
                        .IsUnique();

                    b.HasIndex("userId");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("Community.core.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<int?>("CoursescoursId")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.HasIndex("CoursescoursId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Community.core.Models.Teacher", b =>
                {
                    b.HasOne("Community.core.Models.Courses", "courses")
                        .WithOne("Teacher")
                        .HasForeignKey("Community.core.Models.Teacher", "CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Community.core.Models.User", null)
                        .WithMany("Teachers")
                        .HasForeignKey("userId");

                    b.Navigation("courses");
                });

            modelBuilder.Entity("Community.core.Models.User", b =>
                {
                    b.HasOne("Community.core.Models.Courses", null)
                        .WithMany("Users")
                        .HasForeignKey("CoursescoursId");
                });

            modelBuilder.Entity("Community.core.Models.Courses", b =>
                {
                    b.Navigation("Teacher")
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Community.core.Models.User", b =>
                {
                    b.Navigation("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
